name: Release to PyPI

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write        # push tag + create release
  id-token: write        # OIDC for PyPI

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # required for tags

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Configure git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Get version
        id: version
        run: |
          echo "version=$(uv version --short)" >> $GITHUB_OUTPUT

      - name: Verify changelog
        run: |
          grep -q "## \\[${{ steps.version.outputs.version }}\\]" CHANGELOG.md

      - name: Build package
        run: |
          uv build

      - name: Determine target
        id: target
        run: |
          echo "repo=pypi" >> $GITHUB_OUTPUT
          echo "prerelease=false" >> $GITHUB_OUTPUT

#      - name: Determine target
#        id: target
#        run: |
#          if echo "${{ steps.version.outputs.version }}" | grep -Eq '(a|b|rc)[0-9]+$'; then
#            echo "repo=testpypi" >> $GITHUB_OUTPUT
#            echo "prerelease=true" >> $GITHUB_OUTPUT
#          else
#            echo "repo=pypi" >> $GITHUB_OUTPUT
#            echo "prerelease=false" >> $GITHUB_OUTPUT
#          fi

      - name: Publish
        run: |
          if [ "${{ steps.target.outputs.repo }}" = "testpypi" ]; then
            uv publish --index testpypi
          else
            uv publish
          fi

      - name: Extract release notes
        id: notes
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          awk "
            /^## \\[$VERSION\\]/ {flag=1; next}
            /^## \\[/ {flag=0}
            flag {print}
          " CHANGELOG.md > release_notes.txt

      - name: GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.version.outputs.version }}
          name: v${{ steps.version.outputs.version }}
          prerelease: ${{ steps.target.outputs.prerelease }}
          body_path: release_notes.txt

# WHEN PR titles are clean then use this
#      - name: Create GitHub Release
#        uses: softprops/action-gh-release@v2
#        with:
#          tag_name: v${{ steps.version.outputs.version }}
#          name: v${{ steps.version.outputs.version }}
#          generate_release_notes: true

